language: node_js
node_js:
- '4'
env:
  global:
    secure: IXdAXCoHrOlz3tIp9441BAcIyUfplagPgaPm57tQaQ65yL21RuMWJeFSGQtsZDb5vNgV5781V60wRp4/GFAcTKSPOIhzTvFxFruTAKu1sXJOTPhqN6wwiByvsKjuQr+I5rj/3T934X7eqElOz+aEYkVNqLA1yjmeIarfDPQOGwoBBXU7RGof0LbALBb8EXAAi5q0nXk6l0HJkjCLYHpbZORPahkhSl+6FF8+jK+AF0WplEx3PVagyDMfgVm3ahgRfCG30Gi60FJqNyRA6Z1QgemzCjPUPisaRHYkhVnnGcxddK1Gx7xN1F0L2BinRlxbSjc69GCdTnjMQzXI9mxacKEwajHIPl0pwSwUZq1okJUD6Dsi2aG7BaoJWgndi9ZD/rlN29nbemlJ3oCTUGPgsEXoF0WE5CnwUbEtlxEK5JI520pc5ZmB2yZevf0ULZo43RmCi4XMCoDNZiD4yoyeUSkPos5DPxqtX3JbmIEzZgQpyhFcHDb9JiIReFTPs6cjYM6GXrAoASEwxjzCyjrbSmcDSesM0P2HfxzcBcpCHBLcRmyxJaqj9sXPAoZPYj0ppa8iisrpXxHF8+PxvcdiZBBKzNN7fZ9k63d4LkSdRUPqKaWuQde2ndGJ3OZa3z7dS7Up6b+uhXLFBiTA2E2vHVUJjVnsJFE4i5rjPTqLDaQ=
